spring:
  application:
    name: dubbo-provider-demo
server:
  port: 9999


dubbo:
  scan:
    base-packages: com.ygb.dubboproduction.provider
  registry:
    address: zookeeper://192.168.55.128:2181?timeout=10000
  protocol:
    name: dubbo
    port: 20880